// Code generated by Kitex v0.4.4. DO NOT EDIT.

package favouriteservice

import (
	favourite "aweme_kitex/cmd/favourite/kitex_gen/favourite"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FavouriteAction(ctx context.Context, req *favourite.FavouriteActionRequest, callOptions ...callopt.Option) (r *favourite.FavouriteActionResponse, err error)
	FavouriteList(ctx context.Context, req *favourite.FavouriteListRequest, callOptions ...callopt.Option) (r *favourite.FavouriteListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFavouriteServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFavouriteServiceClient struct {
	*kClient
}

func (p *kFavouriteServiceClient) FavouriteAction(ctx context.Context, req *favourite.FavouriteActionRequest, callOptions ...callopt.Option) (r *favourite.FavouriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavouriteAction(ctx, req)
}

func (p *kFavouriteServiceClient) FavouriteList(ctx context.Context, req *favourite.FavouriteListRequest, callOptions ...callopt.Option) (r *favourite.FavouriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavouriteList(ctx, req)
}
